export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const CLEAN_ALERT = 'CLEAN_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';
export const LOGOUT = 'LOGOUT';

export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';

export const CLEAR_STATE = 'CLEAR_STATE';
